#!/usr/bin/env ruby

require_relative 'lib/rbrpn/calc'
require_relative 'lib/rbrpn/parser'

calc = RPNCalc.new
parser = RPNParser.new calc

ARGF.lines do |line|
  
  if line =~ /[qQ]/ 
    break
  end

  result = parser.parse line
  puts result if result
end
